# Generated by Django 2.1.15 on 2020-05-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_update', models.DateField()),
                ('num_seasons', models.IntegerField()),
                ('num_eps', models.IntegerField()),
                ('thum_img_url', models.CharField(max_length=255)),
                ('banner_img_url', models.CharField(blank=True, max_length=255)),
                ('raiting', models.FloatField()),
            ],
        ),
    ]
