# Generated by Django 2.1.15 on 2020-05-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='is_finished',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
