# Generated by Django 2.1.15 on 2020-05-21 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_show_is_finished'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='raiting',
            new_name='rating',
        ),
    ]
