# Generated by Django 2.1.15 on 2020-05-21 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_update', models.DateField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Season')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Show')),
            ],
        ),
    ]
