# Generated by Django 2.1.15 on 2020-05-24 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_ep_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255)),
                ('subheader', models.CharField(max_length=255)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Show')),
            ],
        ),
    ]
